CREATE DATABASE AJUDAE;
USE AJUDAE;

CREATE TABLE CLIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
SENHA VARCHAR(255) NOT NULL,
TELEFONE VARCHAR(20),
DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FREELANCERS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
SENHA VARCHAR(255) NOT NULL,
TELEFONE VARCHAR(20),
ESPECIALIDADE VARCHAR(200),
DESCRICAO TEXT,
DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ENDERECOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
USUARIO_ID INT NOT NULL,
TIPO ENUM('cliente', 'freelancer') NOT NULL,
RUA VARCHAR(100),
NUMERO VARCHAR(10),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(15),
FOREIGN KEY (usuario_id)
REFERENCES clientes(id)
ON DELETE CASCADE
);

	